

package com.duckduckgo.app.global.rating

const val MINIMUM_SEARCHES_THRESHOLD = 5
const val MINIMUM_DAYS_USAGE_BEFORE_FIRST_PROMPT = 3
const val MINIMUM_DAYS_USAGE_SINCE_INITIAL_PROMPT_BEFORE_SECOND_PROMPT = 4
