

package com.duckduckgo.common.ui.themepreview.ui.component

enum class Component {
    BUTTON,
    FAB,
    EXPANDABLE_LAYOUT,
    CARD,
    TOP_APP_BAR,
    CHIP,
    DRAWER,
    TEXT_FIELD,
    BOTTOM_NAVIGATION,
    SWITCH,
    RADIO_BUTTON,
    CHECKBOX,
    SLIDER,
    BOTTOM_APP_BAR,
    TABS,
    SNACKBAR,
    REMOTE_MESSAGE,
    INFO_PANEL,
    DIALOG,
    BOTTOM_SHEET,
    IMAGE,
    SEARCH_BAR,
    MENU_ITEM,
    POPUP_MENU_ITEM,
    SECTION_HEADER_LIST_ITEM,
    SINGLE_LINE_LIST_ITEM,
    TWO_LINE_LIST_ITEM,
    SETTINGS_LIST_ITEM,
    SECTION_DIVIDER,
}
